# Generated by Django 3.1.2 on 2020-10-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '__first__'),
        ('geocoding', '0002_auto_20201006_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='GCS',
        ),
        migrations.RemoveField(
            model_name='address',
            name='PCS',
        ),
        migrations.AddField(
            model_name='address',
            name='geom_srid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gis.postgisspatialrefsys'),
        ),
    ]
