# Generated by Django 3.1.2 on 2020-10-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0003_auto_20201006_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
